# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ra', models.IntegerField(db_column='RA', unique=True)),
                ('password', models.CharField(db_column='Senha', max_length=200)),
                ('nome', models.CharField(db_column='Nome', max_length=100)),
                ('email', models.EmailField(db_column='E-mail', max_length=50)),
                ('celular', models.CharField(db_column='Celular', max_length=11)),
                ('perfil', models.CharField(db_column='Perfil', max_length=1)),
                ('ativo', models.BooleanField(db_column='Ativo', default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Arquivosquestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivoquestao', models.CharField(blank=True, db_column='ArquivoQuestao', max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arquivosrespostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivoresposta', models.CharField(db_column='ArquivoResposta', max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(db_column='Sigla', max_length=5, unique=True, verbose_name='Sigla do curso')),
                ('nome', models.CharField(db_column='Nome', max_length=50, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Link')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Imagem do curso')),
                ('sobre', models.TextField(blank=True, verbose_name='Sobre o Curso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cursoturma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=240, unique=True)),
                ('cargahoraria', models.SmallIntegerField(db_column='CargaHoraria')),
                ('teoria', models.DecimalField(db_column='Teoria', decimal_places=0, max_digits=3)),
                ('pratica', models.DecimalField(db_column='Pratica', decimal_places=0, max_digits=3)),
                ('ementa', models.TextField(db_column='Ementa')),
                ('competencias', models.TextField(db_column='Competencias')),
                ('habilidades', models.TextField(db_column='Habilidades')),
                ('conteudo', models.TextField(db_column='Conteudo')),
                ('bibliografia_basica', models.TextField(db_column='Bibliografia_Basica')),
                ('biblioteca_complementar', models.TextField(db_column='Biblioteca_complementar')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anoofertado', models.SmallIntegerField(db_column='AnoOfertado', unique=True)),
                ('semestreofertado', models.CharField(db_column='SemestreOfertado', max_length=1, unique=True)),
                ('nome_disciplina', models.ForeignKey(db_column='Nome_Disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Gradecurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(db_column='Ano', unique=True)),
                ('semestre', models.CharField(db_column='Semestre', max_length=1, unique=True)),
                ('sigla_curso', models.ForeignKey(db_column='Sigla_Curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_ofertado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ano_Ofertado_Matricula', to='core.Disciplinaofertada')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroperiodo', models.SmallIntegerField(db_column='NumeroPeriodo', unique=True)),
                ('ano_grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ano_Grade_Periodo', to='core.Gradecurricular')),
                ('semestre_grade', models.ForeignKey(db_column='Semestre_Grade', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Gradecurricular')),
                ('sigla_curso', models.ForeignKey(db_column='Sigla_Curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Periododisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ano_Grade_periodo_dis', to='core.Gradecurricular')),
                ('nome_disciplina', models.ForeignKey(db_column='Nome_Disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina')),
                ('numero_periodo', models.ForeignKey(db_column='Numero_Periodo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Periodo')),
                ('semestre_grade', models.ForeignKey(db_column='Semestre_Grade', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Gradecurricular')),
                ('sigla_curso', models.ForeignKey(db_column='Sigla_Curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroquestao', models.IntegerField(db_column='NumeroQuestao', unique=True)),
                ('datalimiteentrega', models.CharField(db_column='DataLimiteEntrega', max_length=10)),
                ('descricao', models.TextField(db_column='Descricao')),
                ('data', models.CharField(db_column='Data', max_length=10)),
                ('ano_ofertado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ano_Ofertado_Questao', to='core.Disciplinaofertada')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField(db_column='RA_Aluno', unique=True)),
                ('dataavaliacao', models.CharField(db_column='DataAvaliacao', max_length=10)),
                ('nota', models.DecimalField(db_column='Nota', decimal_places=2, max_digits=4)),
                ('avaliacao', models.TextField(db_column='Avaliacao')),
                ('descricao', models.TextField(db_column='Descricao')),
                ('datadeenvio', models.CharField(db_column='DataDeEnvio', max_length=10)),
                ('ano_ofertado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ano_Ofertado_Resposta', to='core.Disciplinaofertada')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turma', models.CharField(db_column='Id_Turma', max_length=1, unique=True)),
                ('turno', models.CharField(db_column='Turno', max_length=15)),
                ('ano_ofertado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ano_Ofertado', to='core.Disciplinaofertada')),
                ('nome_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Nome_Disciplina', to='core.Disciplina')),
                ('semestre_ofertado', models.ForeignKey(db_column='Semestre_Ofertado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplinaofertada')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('imagemAluno', models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Imagem do Aluno')),
                ('sigla_curso', models.ForeignKey(db_column='Sigla_Curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
                ('apelido', models.CharField(db_column='Apelido', max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
        migrations.AddField(
            model_name='resposta',
            name='id_turma',
            field=models.ForeignKey(db_column='Id_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='nome_disciplina',
            field=models.ForeignKey(db_column='Nome_Disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='numero_questao',
            field=models.ForeignKey(db_column='Numero_Questao', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Questao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='Semestre_Ofertado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='questao',
            name='id_turma',
            field=models.ForeignKey(db_column='Id_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='questao',
            name='nome_discplina',
            field=models.ForeignKey(db_column='Nome_Discplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina'),
        ),
        migrations.AddField(
            model_name='questao',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='Semestre_Ofertado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_turma',
            field=models.ForeignKey(db_column='Id_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='nome_disciplina',
            field=models.ForeignKey(db_column='Nome_Disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='Semestre_Ofertado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='ano_ofertado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ano_Ofertado_Curso_Turma', to='core.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='id_turma',
            field=models.ForeignKey(db_column='Id_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='nome_disciplina',
            field=models.ForeignKey(db_column='Nome_Disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='Semestre_Ofertado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='sigla_curso',
            field=models.ForeignKey(db_column='Sigla_Curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso'),
        ),
        migrations.AddField(
            model_name='arquivosrespostas',
            name='ano_ofertado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ano_Ofertado_Arquivo_Resposta', to='core.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='arquivosrespostas',
            name='id_turma',
            field=models.ForeignKey(db_column='Id_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='arquivosrespostas',
            name='nome_disciplina',
            field=models.ForeignKey(db_column='Nome_Disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina'),
        ),
        migrations.AddField(
            model_name='arquivosrespostas',
            name='numero_questao',
            field=models.ForeignKey(db_column='Numero_Questao', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Questao'),
        ),
        migrations.AddField(
            model_name='arquivosrespostas',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='Semestre_Ofertado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='arquivosquestao',
            name='ano_ofertado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ano_Ofertado_Arquivo_Questao', to='core.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='arquivosquestao',
            name='id_turma',
            field=models.ForeignKey(db_column='Id_Turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='arquivosquestao',
            name='nome_disciplina',
            field=models.ForeignKey(db_column='Nome_Disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina'),
        ),
        migrations.AddField(
            model_name='arquivosquestao',
            name='numero_questao',
            field=models.ForeignKey(db_column='Numero_Questao', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Questao'),
        ),
        migrations.AddField(
            model_name='arquivosquestao',
            name='semestre_ofertado',
            field=models.ForeignKey(db_column='Semestre_Ofertado', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplinaofertada'),
        ),
        migrations.AddField(
            model_name='turma',
            name='ra_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='RA_Professor', to='core.Professor'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='ra_aluno',
            field=models.ForeignKey(db_column='RA_Aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno'),
        ),
        migrations.AddField(
            model_name='arquivosrespostas',
            name='ra_aluno',
            field=models.ForeignKey(db_column='RA_Aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno'),
        ),
    ]
