# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField(db_column='RA_Aluno', unique=True)),
                ('nome', models.CharField(db_column='Nome', max_length=120)),
                ('email', models.CharField(db_column='Email', max_length=80)),
                ('celular', models.CharField(db_column='Celular', max_length=11)),
            ],
            options={
                'db_table': 'Aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arquivosquestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivoquestao', models.CharField(blank=True, db_column='ArquivoQuestao', max_length=500, null=True, unique=True)),
            ],
            options={
                'db_table': 'ArquivosQuestao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arquivosrespostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivoresposta', models.CharField(db_column='ArquivoResposta', max_length=500, unique=True)),
            ],
            options={
                'db_table': 'ArquivosRespostas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(db_column='Sigla', max_length=5, unique=True)),
                ('nome', models.CharField(db_column='Nome', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursoturma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'CursoTurma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=240, unique=True)),
                ('cargahoraria', models.SmallIntegerField(db_column='CargaHoraria')),
                ('teoria', models.DecimalField(db_column='Teoria', decimal_places=0, max_digits=3)),
                ('pratica', models.DecimalField(db_column='Pratica', decimal_places=0, max_digits=3)),
                ('ementa', models.TextField(db_column='Ementa')),
                ('competencias', models.TextField(db_column='Competencias')),
                ('habilidades', models.TextField(db_column='Habilidades')),
                ('conteudo', models.TextField(db_column='Conteudo')),
                ('bibliografia_basica', models.TextField(db_column='Bibliografia_Basica')),
                ('biblioteca_complementar', models.TextField(db_column='Biblioteca_complementar')),
            ],
            options={
                'db_table': 'Disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anoofertado', models.SmallIntegerField(db_column='AnoOfertado', unique=True)),
                ('semestreofertado', models.CharField(db_column='SemestreOfertado', max_length=1, unique=True)),
            ],
            options={
                'db_table': 'DisciplinaOfertada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gradecurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(db_column='Ano', unique=True)),
                ('semestre', models.CharField(db_column='Semestre', max_length=1, unique=True)),
            ],
            options={
                'db_table': 'GradeCurricular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Matricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroperiodo', models.SmallIntegerField(db_column='NumeroPeriodo', unique=True)),
            ],
            options={
                'db_table': 'Periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periododisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'PeriodoDisciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_professor', models.IntegerField(db_column='RA_Professor', unique=True)),
                ('apelido', models.CharField(db_column='Apelido', max_length=30, unique=True)),
                ('nome', models.CharField(db_column='Nome', max_length=30)),
                ('email', models.CharField(db_column='Email', max_length=120)),
                ('celular', models.CharField(db_column='Celular', max_length=11)),
            ],
            options={
                'db_table': 'Professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroquestao', models.IntegerField(db_column='NumeroQuestao', unique=True)),
                ('datalimiteentrega', models.CharField(db_column='DataLimiteEntrega', max_length=10)),
                ('descricao', models.TextField(db_column='Descricao')),
                ('data', models.CharField(db_column='Data', max_length=10)),
            ],
            options={
                'db_table': 'Questao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_aluno', models.IntegerField(db_column='RA_Aluno', unique=True)),
                ('dataavaliacao', models.CharField(db_column='DataAvaliacao', max_length=10)),
                ('nota', models.DecimalField(db_column='Nota', decimal_places=2, max_digits=4)),
                ('avaliacao', models.TextField(db_column='Avaliacao')),
                ('descricao', models.TextField(db_column='Descricao')),
                ('datadeenvio', models.CharField(db_column='DataDeEnvio', max_length=10)),
            ],
            options={
                'db_table': 'Resposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turma', models.CharField(db_column='Id_Turma', max_length=1, unique=True)),
                ('turno', models.CharField(db_column='Turno', max_length=15)),
            ],
            options={
                'db_table': 'Turma',
                'managed': False,
            },
        ),
    ]
