# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('idaluno', models.IntegerField(db_column='IdAluno', primary_key=True, serialize=False)),
                ('ra_aluno', models.IntegerField(db_column='RA_Aluno')),
                ('nome', models.CharField(db_column='Nome', max_length=120)),
                ('email', models.CharField(db_column='Email', max_length=80)),
                ('celular', models.CharField(db_column='Celular', max_length=11)),
            ],
            options={
                'db_table': 'Aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arquivosquestao',
            fields=[
                ('idarquivosquestao', models.IntegerField(db_column='IdArquivosQuestao', primary_key=True, serialize=False)),
                ('arquivoquestao', models.CharField(blank=True, db_column='ArquivoQuestao', max_length=500, null=True)),
            ],
            options={
                'db_table': 'ArquivosQuestao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Arquivosrespostas',
            fields=[
                ('idarquivoresposta', models.IntegerField(db_column='IdArquivoResposta', primary_key=True, serialize=False)),
                ('arquivoresposta', models.CharField(db_column='ArquivoResposta', max_length=500)),
            ],
            options={
                'db_table': 'ArquivosRespostas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('carga_horaria', models.IntegerField()),
                ('professor', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('ativo', models.BooleanField()),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'core_curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.IntegerField(db_column='IdCurso', primary_key=True, serialize=False)),
                ('sigla', models.CharField(db_column='Sigla', max_length=5)),
                ('nome', models.CharField(db_column='Nome', max_length=50)),
            ],
            options={
                'db_table': 'Curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursoturma',
            fields=[
                ('idcursoturma', models.IntegerField(db_column='IdCursoTurma', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CursoTurma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('iddisciplina', models.IntegerField(db_column='IdDisciplina', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=240)),
                ('cargahoraria', models.SmallIntegerField(db_column='CargaHoraria')),
                ('teoria', models.DecimalField(db_column='Teoria', decimal_places=0, max_digits=3)),
                ('pratica', models.DecimalField(db_column='Pratica', decimal_places=0, max_digits=3)),
                ('ementa', models.TextField(db_column='Ementa')),
                ('competencias', models.TextField(db_column='Competencias')),
                ('habilidades', models.TextField(db_column='Habilidades')),
                ('conteudo', models.TextField(db_column='Conteudo')),
                ('bibliografia_basica', models.TextField(db_column='Bibliografia_Basica')),
                ('biblioteca_complementar', models.TextField(db_column='Biblioteca_complementar')),
            ],
            options={
                'db_table': 'Disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('iddisciplinaofertada', models.IntegerField(db_column='IdDisciplinaOfertada', primary_key=True, serialize=False)),
                ('anoofertado', models.SmallIntegerField(db_column='AnoOfertado')),
                ('semestreofertado', models.CharField(db_column='SemestreOfertado', max_length=1)),
            ],
            options={
                'db_table': 'DisciplinaOfertada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gradecurricular',
            fields=[
                ('idgradecurricular', models.IntegerField(db_column='IdGradeCurricular', primary_key=True, serialize=False)),
                ('ano', models.IntegerField(db_column='Ano')),
                ('semestre', models.CharField(db_column='Semestre', max_length=1)),
            ],
            options={
                'db_table': 'GradeCurricular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('idmatricula', models.IntegerField(db_column='IdMatricula', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Matricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('idperiodo', models.IntegerField(db_column='IdPeriodo', primary_key=True, serialize=False)),
                ('numeroperiodo', models.SmallIntegerField(db_column='NumeroPeriodo')),
            ],
            options={
                'db_table': 'Periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periododisciplina',
            fields=[
                ('idperiododisciplina', models.IntegerField(db_column='IdPeriodoDisciplina', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PeriodoDisciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('idprofessor', models.IntegerField(db_column='IdProfessor', primary_key=True, serialize=False)),
                ('ra_professor', models.IntegerField(db_column='RA_Professor')),
                ('apelido', models.CharField(db_column='Apelido', max_length=30)),
                ('nome', models.CharField(db_column='Nome', max_length=30)),
                ('email', models.CharField(db_column='Email', max_length=120)),
                ('celular', models.CharField(db_column='Celular', max_length=11)),
            ],
            options={
                'db_table': 'Professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('idquestao', models.IntegerField(db_column='IdQuestao', primary_key=True, serialize=False)),
                ('numeroquestao', models.IntegerField(db_column='NumeroQuestao')),
                ('datalimiteentrega', models.CharField(db_column='DataLimiteEntrega', max_length=10)),
                ('descricao', models.TextField(db_column='Descricao')),
                ('data', models.CharField(db_column='Data', max_length=10)),
            ],
            options={
                'db_table': 'Questao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('idresposta', models.IntegerField(db_column='IdResposta', primary_key=True, serialize=False)),
                ('dataavaliacao', models.CharField(db_column='DataAvaliacao', max_length=10)),
                ('nota', models.DecimalField(db_column='Nota', decimal_places=2, max_digits=4)),
                ('avaliacao', models.TextField(db_column='Avaliacao')),
                ('descricao', models.TextField(db_column='Descricao')),
                ('datadeenvio', models.CharField(db_column='DataDeEnvio', max_length=10)),
            ],
            options={
                'db_table': 'Resposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('idturma', models.IntegerField(db_column='IdTurma', primary_key=True, serialize=False)),
                ('turno', models.CharField(db_column='Turno', max_length=15)),
            ],
            options={
                'db_table': 'Turma',
                'managed': False,
            },
        ),
    ]
