# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro_boletim',
            options={'ordering': ['curso'], 'verbose_name': 'Boletim', 'verbose_name_plural': 'Boletins'},
        ),
        migrations.AlterModelOptions(
            name='gradecurricular',
            options={'ordering': ['sigla_curso'], 'verbose_name': 'Grade Curricular', 'verbose_name_plural': 'Grades Curriculares'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='gradecurricular',
            name='ano',
            field=models.SmallIntegerField(db_column='Ano'),
        ),
        migrations.AlterField(
            model_name='gradecurricular',
            name='semestre',
            field=models.CharField(db_column='Semestre', max_length=1),
        ),
    ]
