# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resposta',
            options={},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ra_aluno',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='ra_professor',
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, default=1324, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, default=1234, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario'),
            preserve_default=False,
        ),
    ]
