# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171127_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['ra_aluno'], 'verbose_name': 'Matricula', 'verbose_name_plural': 'Matriculas'},
        ),
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['sigla_curso'], 'verbose_name': 'Periodo', 'verbose_name_plural': 'Periodos'},
        ),
        migrations.AlterModelOptions(
            name='periododisciplina',
            options={'ordering': ['sigla_curso'], 'verbose_name': 'Periodo e Disciplina', 'verbose_name_plural': 'Periodos e Disciplinas'},
        ),
        migrations.AlterField(
            model_name='periodo',
            name='ano_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ano', to='core.Gradecurricular'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='semestre_grade',
            field=models.IntegerField(db_column='Semestre_Grade'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='sigla_curso',
            field=models.ForeignKey(db_column='Sigla_Curso', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Curso', to='core.Curso'),
        ),
    ]
