# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171125_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resposta',
            options={'managed': False},
        ),
    ]
