# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171128_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['nome_disciplina'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
    ]
