# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171117_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='slug',
            field=models.SlugField(verbose_name='Link'),
        ),
    ]
