# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171118_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sobre',
            field=models.TextField(blank=True, verbose_name='Sobre o Curso'),
        ),
    ]
