# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171127_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Boletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MB1', models.SmallIntegerField(blank=True, null=True, verbose_name='MB1')),
                ('SUB1', models.SmallIntegerField(blank=True, null=True, verbose_name='SUB1')),
                ('MB2', models.SmallIntegerField(blank=True, null=True, verbose_name='MB2')),
                ('SUB2', models.SmallIntegerField(blank=True, null=True, verbose_name='sub2')),
                ('regular', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('curso', models.ForeignKey(db_column='Curso', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Curso')),
                ('nome_aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Nome', to='core.Aluno')),
                ('nome_disciplina', models.ForeignKey(db_column='Nome_Discplina', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Disciplina')),
            ],
        ),
    ]
