# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171106_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': False},
        ),
    ]
