# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionario',
            options={'managed': False},
        ),
    ]
