# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171127_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro_boletim',
            old_name='ra',
            new_name='ra_aluno',
        ),
    ]
